# Generated by Django 6.0 on 2025-12-17 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('id_camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.camion')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('camara', models.IntegerField()),
                ('ruta_archivo', models.FileField(upload_to='videos/')),
                ('hora_inicio', models.TimeField()),
                ('duracion', models.DurationField()),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.turno')),
            ],
        ),
    ]
