# Generated by Django 6.0 on 2025-12-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_turno_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='camara',
            field=models.IntegerField(choices=[(1, 'Cámara 1'), (2, 'Cámara 2'), (3, 'Cámara 3'), (4, 'Cámara 4')]),
        ),
    ]
