# Generated by Django 6.0 on 2025-12-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_video_camara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duracion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
