# Generated by Django 6.0 on 2025-12-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_video_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
