# Generated by Django 6.0 on 2025-12-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_video_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='estado',
            field=models.CharField(choices=[('procesando', 'Procesando'), ('listo', 'Listo'), ('error', 'Error')], default='procesando', max_length=20),
        ),
    ]
