# Generated by Django 6.0 on 2025-12-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_video_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='fin_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='inicio_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
