# Generated by Django 6.0 on 2025-02-20 00:00

import datetime
import mimetypes
from django.db import migrations, models


def set_video_times_and_mimetype(apps, schema_editor):
    Video = apps.get_model('dashboard', 'Video')
    today = datetime.date.today()

    for video in Video.objects.all():
        inicio = video.inicio_timestamp or datetime.time(0, 0)
        if isinstance(inicio, datetime.datetime):
            inicio = inicio.time()

        fin = None
        if video.duracion is not None:
            fin = (
                datetime.datetime.combine(today, inicio)
                + datetime.timedelta(seconds=float(video.duracion))
            ).time()

        guessed_mime = mimetypes.guess_type(getattr(video.ruta_archivo, "name", "") or "")[0] or ""

        video.inicio_timestamp = inicio
        video.fin_timestamp = fin
        video.mimetype = video.mimetype or guessed_mime
        video.save(update_fields=["inicio_timestamp", "fin_timestamp", "mimetype"])


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_video_inicio_fin_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='mimetype',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='inicio_timestamp',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='fin_timestamp',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RunPython(set_video_times_and_mimetype, migrations.RunPython.noop),
    ]
