# Generated by Django 6.0 on 2025-02-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_video_timefields_mimetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
