# Generated by Django 6.0 on 2025-02-20 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_operador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidente', models.CharField(max_length=100)),
                ('severidad', models.CharField(max_length=50)),
                ('tiempo_en_video', models.IntegerField(help_text='Segundos desde el inicio del video')),
                ('descripcion', models.TextField(blank=True, default='')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.turno')),
            ],
        ),
    ]
