# Generated by Django 6.0 on 2025-02-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_incidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='severidad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='tipo_incidente',
            field=models.CharField(choices=[('exceso_velocidad', 'Exceso de velocidad'), ('frenado_brusco', 'Frenado brusco'), ('colision', 'Colisión'), ('otro', 'Otro')], max_length=50),
        ),
    ]
