# Generated by Django 6.0 on 2025-02-20 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_incidente_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.operador'),
        ),
    ]
