# Generated by Django 5.1.4 on 2026-01-04 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_turno_operador_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
