# Generated by Django 5.1.4 on 2026-01-05 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_turno_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='tipo_turno',
            field=models.CharField(blank=True, choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.PositiveIntegerField()),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='dashboard.operador')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='dashboard.turno')),
            ],
            options={
                'unique_together': {('semana', 'turno')},
            },
        ),
        migrations.DeleteModel(
            name='TipoTurno',
        ),
    ]
