# Generated by Django 5.1.4 on 2026-01-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_turno_tipo_turno_turno_completado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
    ]
