# Generated by Django 5.1.4 on 2026-01-06 18:33

from django.db import migrations, models


def add_camion_fields(apps, schema_editor):
    Camion = apps.get_model('dashboard', 'Camion')
    table = Camion._meta.db_table
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table)

    def has_column(col_name):
        for col in description:
            name = getattr(col, "name", col[0])
            if name == col_name:
                return True
        return False

    if not has_column("ano"):
        field = models.PositiveIntegerField(null=True, blank=True)
        field.set_attributes_from_name("ano")
        schema_editor.add_field(Camion, field)

    if not has_column("marca"):
        field = models.CharField(max_length=100, blank=True, default="")
        field.set_attributes_from_name("marca")
        schema_editor.add_field(Camion, field)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_operador_estado'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_camion_fields, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='camion',
                    name='ano',
                    field=models.PositiveIntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='camion',
                    name='marca',
                    field=models.CharField(blank=True, default='', max_length=100),
                ),
            ],
        ),
    ]
