# Generated by Django 5.1.4 on 2026-01-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_mantenimiento_camion_ultimo_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
