# Generated by Django 5.1.4 on 2026-01-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_camion_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='tipo_incidente',
            field=models.CharField(
                choices=[
                    ('frenado_brusco', 'Frenado Brusco'),
                    ('exceso_velocidad', 'Exceso Velocidad'),
                    ('colision', 'Colisión'),
                    ('distraccion', 'Distracción'),
                    ('fatiga_sueno', 'Fatiga / Sueño'),
                    ('otro', 'Otro'),
                ],
                max_length=50,
            ),
        ),
    ]
