# Generated by Django 5.1.4 on 2026-01-16 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0025_alter_incidente_tipo_incidente"),
    ]

    operations = [
        migrations.CreateModel(
            name="VelocidadVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("segundo", models.PositiveIntegerField()),
                ("velocidad_kmh", models.FloatField()),
                ("timestamp_csv", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="velocidades",
                        to="dashboard.video",
                    ),
                ),
            ],
            options={
                "unique_together": {("video", "segundo")},
            },
        ),
        migrations.AddIndex(
            model_name="velocidadvideo",
            index=models.Index(
                fields=["video", "segundo"], name="velocidad_video_segundo_idx"
            ),
        ),
    ]
