# Generated by Django 5.1.4 on 2026-01-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0026_velocidadvideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="velocidadvideo",
            name="interpolado",
            field=models.BooleanField(default=False),
        ),
    ]
