# Generated by Django 5.1.4 on 2026-01-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_velocidadvideo_interpolado"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="fecha_inicio",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
