# Generated by Django 5.1.4 on 2026-01-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_video_fecha_inicio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="hora_inicio",
        ),
    ]
