# Generated by Django 5.1.4 on 2026-01-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_remove_video_hora_inicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="velocidadvideo",
            name="sin_datos",
            field=models.BooleanField(default=False),
        ),
    ]
