# Generated by Django 5.1.4 on 2026-02-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_velocidadvideo_sin_datos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='camion',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='ultimo_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='operador',
        ),
        migrations.DeleteModel(
            name='AsignacionTurno',
        ),
        migrations.DeleteModel(
            name='Mantenimiento',
        ),
        migrations.DeleteModel(
            name='Operador',
        ),
    ]
