# Generated by Django 5.1.4 on 2026-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0030_velocidadvideo_sin_datos"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="origen_modificado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="origen_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="video",
            name="origen_tamano_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="ruta_origen",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["ruta_origen", "id_turno", "camara"],
                name="video_origen_turno_camara_idx",
            ),
        ),
    ]
