# Generated by Django 5.1.4 on 2026-04-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0031_video_origen_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="grupo_origen",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="video",
            name="segmentos_origen",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["grupo_origen", "id_turno", "camara"],
                name="video_grupo_turno_camara_idx",
            ),
        ),
    ]
