# Generated by Django 5.1.4 on 2026-02-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_remove_mantenimiento_camion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='tipo_turno',
            field=models.CharField(blank=True, choices=[('manana', 'Día'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=10, null=True),
        ),
    ]
