# Generated by Codex on 2026-02-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0032_alter_turno_tipo_turno"),
    ]

    operations = [
        migrations.AddField(
            model_name="camion",
            name="carpeta_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
    ]
