# Generated by Django 5.1.4 on 2026-04-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0032_video_grupo_segmentos"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="detalle_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="video",
            name="error_tipo",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="video",
            name="fecha_fin",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="mapa_segmentos",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
