# Generated by Codex on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0033_camion_carpeta_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidente",
            name="tipo_incidente",
            field=models.CharField(
                choices=[
                    ("frenado_brusco", "Frenado o Giro Brusco"),
                    ("exceso_velocidad", "Exceso de Velocidad"),
                    ("colision", "Impacto o Colisión"),
                    ("sobrecarga", "Sobrecarga"),
                    ("ingreso_zona_restringida", "Ingreso a Zona Restringida o Peatonal"),
                    (
                        "falla_mecanica_hidraulica_electrica",
                        "Falla Mecánica, Hidráulica o Eléctrica",
                    ),
                    ("perdida_gps_comunicacion", "Pérdida de GPS o Comunicación"),
                    ("distraccion", "Distracción"),
                    ("fatiga_sueno", "Fatiga / Sueño"),
                    ("otro", "Otro"),
                ],
                max_length=50,
            ),
        ),
    ]
