# Generated by Codex on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0036_alter_incidente_tipo_incidente"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="proximo_reintento_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="reintentos",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="ultimo_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="video",
            name="estado",
            field=models.CharField(
                choices=[
                    ("procesando", "Procesando"),
                    ("listo", "Listo"),
                    ("error", "Error"),
                    ("error_permanente", "Error permanente"),
                ],
                default="procesando",
                max_length=20,
            ),
        ),
    ]
