# Generated by Codex on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0037_video_reintentos_error_permanente"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidente",
            name="velocidad_kmh",
            field=models.FloatField(
                blank=True,
                help_text="Velocidad (km/h) capturada automáticamente al momento del reporte.",
                null=True,
            ),
        ),
    ]
