# Generated by Codex on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0038_incidente_velocidad_kmh"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="estado_velocidades",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("importada", "Importada"),
                    ("sin_xlsx", "Sin XLSX"),
                    ("error", "Error"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="velocidades_actualizadas_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="velocidades_error",
            field=models.TextField(blank=True, default=""),
        ),
    ]
