# Generated by Codex on 2026-02-21

from django.db import migrations, models


def copiar_velocidades_desde_video(apps, schema_editor):
    VelocidadVideo = apps.get_model("dashboard", "VelocidadVideo")
    VelocidadTurno = apps.get_model("dashboard", "VelocidadTurno")

    batch = []
    qs = VelocidadVideo.objects.select_related("video").order_by("id")
    for velocidad in qs.iterator(chunk_size=2000):
        video = getattr(velocidad, "video", None)
        turno_id = getattr(video, "id_turno_id", None)
        if turno_id is None:
            continue
        batch.append(
            VelocidadTurno(
                turno_id=turno_id,
                segundo=velocidad.segundo,
                velocidad_kmh=velocidad.velocidad_kmh,
                timestamp_csv=velocidad.timestamp_csv,
                interpolado=velocidad.interpolado,
                sin_datos=velocidad.sin_datos,
            )
        )
        if len(batch) >= 2000:
            VelocidadTurno.objects.bulk_create(
                batch,
                batch_size=2000,
                ignore_conflicts=True,
            )
            batch.clear()

    if batch:
        VelocidadTurno.objects.bulk_create(
            batch,
            batch_size=2000,
            ignore_conflicts=True,
        )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0039_video_estado_velocidades"),
    ]

    operations = [
        migrations.CreateModel(
            name="VelocidadTurno",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("segundo", models.PositiveIntegerField()),
                ("velocidad_kmh", models.FloatField()),
                ("timestamp_csv", models.DateTimeField(blank=True, null=True)),
                ("interpolado", models.BooleanField(default=False)),
                ("sin_datos", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="velocidades_turno",
                        to="dashboard.turno",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["turno", "segundo"], name="velocidad_turno_segundo_idx"),
                ],
                "unique_together": {("turno", "segundo")},
            },
        ),
        migrations.RunPython(copiar_velocidades_desde_video, reverse_code=noop_reverse),
    ]
