# Generated by Codex on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0042_video_tiempo_procesamiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="detalle_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="video",
            name="error_tipo",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="video",
            name="fecha_fin",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="grupo_origen",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="video",
            name="origen_modificado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="origen_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="video",
            name="origen_tamano_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="ruta_origen",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="video",
            name="segmentos_origen",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["ruta_origen", "id_turno", "camara"],
                name="video_origen_turno_camara_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["grupo_origen", "id_turno", "camara"],
                name="video_grupo_turno_camara_idx",
            ),
        ),
    ]
