# Generated by Codex on 2026-02-09

import re
from django.db import migrations, models
import django.contrib.auth.validators


def _sanitize_username(value: str) -> str:
    value = (value or "").strip()
    if not value:
        return "user"
    # Allow letters, digits and @/./+/-/_ only
    value = re.sub(r"[^\w.@+-]+", "_", value)
    return value[:150] or "user"


def _populate_usernames(apps, schema_editor):
    Usuario = apps.get_model("usuarios", "Usuario")
    existing = set(
        Usuario.objects.exclude(username__isnull=True)
        .exclude(username__exact="")
        .values_list("username", flat=True)
    )

    for user in Usuario.objects.all().iterator():
        if getattr(user, "username", None):
            continue

        base = _sanitize_username(getattr(user, "email", "") or f"user_{user.pk}")
        candidate = base
        counter = 1
        while candidate in existing:
            candidate = f"{base}_{counter}"
            counter += 1
        user.username = candidate
        user.save(update_fields=["username"])
        existing.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="username",
            field=models.CharField(
                verbose_name="username",
                max_length=150,
                unique=False,
                blank=True,
                null=True,
                help_text=(
                    "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
                ),
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                error_messages={"unique": "A user with that username already exists."},
            ),
        ),
        migrations.RunPython(_populate_usernames, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(
                verbose_name="username",
                max_length=150,
                unique=True,
                help_text=(
                    "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
                ),
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                error_messages={"unique": "A user with that username already exists."},
            ),
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="email",
        ),
    ]
