# Generated by Codex on 2026-02-16

from django.db import migrations


ROLE_ADMINISTRADOR = "Administrador"
ROLE_SUPERVISOR = "Supervisor"

PERMISOS_VIDEO = (
    "view_video",
    "add_video",
    "change_video",
    "delete_video",
)
PERMISOS_INCIDENTE = (
    "view_incidente",
    "add_incidente",
    "change_incidente",
    "delete_incidente",
)


def _obtener_permisos(Permission, app_label, codenames):
    permisos = Permission.objects.filter(
        content_type__app_label=app_label,
        codename__in=codenames,
    )
    encontrados = set(permisos.values_list("codename", flat=True))
    faltantes = sorted(set(codenames) - encontrados)
    if faltantes:
        raise RuntimeError(
            f"No se encontraron permisos en app '{app_label}': {', '.join(faltantes)}"
        )
    return list(permisos)


def crear_roles_y_permisos(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    Usuario = apps.get_model("usuarios", "Usuario")

    grupo_admin, _ = Group.objects.get_or_create(name=ROLE_ADMINISTRADOR)
    grupo_supervisor, _ = Group.objects.get_or_create(name=ROLE_SUPERVISOR)

    permisos_admin = _obtener_permisos(
        Permission,
        "dashboard",
        PERMISOS_VIDEO + PERMISOS_INCIDENTE,
    )
    permisos_supervisor = _obtener_permisos(
        Permission,
        "dashboard",
        ("view_video",) + PERMISOS_INCIDENTE,
    )

    grupo_admin.permissions.set(permisos_admin)
    grupo_supervisor.permissions.set(permisos_supervisor)

    for usuario in Usuario.objects.filter(is_superuser=True).iterator():
        usuario.groups.add(grupo_admin)


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0036_alter_incidente_tipo_incidente"),
        ("usuarios", "0002_username_remove_email"),
    ]

    operations = [
        migrations.RunPython(crear_roles_y_permisos, migrations.RunPython.noop),
    ]
